# Generated by Django 3.0.7 on 2020-07-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('macAddress', models.CharField(max_length=17)),
                ('ipAddress', models.GenericIPAddressField(unpack_ipv4=True)),
                ('serialNumber', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type_category', models.CharField(choices=[('PRT', 'printer'), ('PLC', 'plc'), ('SC', 'security camera')], max_length=15)),
                ('location', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
