# Generated by Django 3.0.7 on 2020-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20200709_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ipAddress',
            new_name='ip_Address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='macAddress',
            new_name='mac_Address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='serialNumber',
            new_name='serial_Number',
        ),
    ]
