# Generated by Django 3.0.7 on 2020-07-09 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200709_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='number_floors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
