# Generated by Django 3.0.7 on 2020-07-09 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200709_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
